ktor:
  application:
    modules:
      - ApplicationKt.module
  deployment:
    port: 8080

storage:
  driverClassName: "com.mysql.cj.jdbc.Driver"
  jdbcUrl: "jdbc:mysql://localhost:3306/trip_share_db"
  user: "johan"
  password: "johan"