services:
  db:
    image: mysql:latest
    container_name: db_permanente
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: johan
      MYSQL_USER: johan
      MYSQL_PASSWORD: johan
    ports:
      - "3306:3306"
    volumes:
      - mysql_data_johan:/var/lib/mysql
      - ./docker/mysql:/docker-entrypoint-initdb.d   

volumes:
  mysql_data_johan: